/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiFeedRouteImport } from './routes/ai-feed'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as CybersecurityRouteImport } from './routes/cybersecurity'
import { Route as HubRouteImport } from './routes/hub'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as VehicleRouteImport } from './routes/vehicle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFeedRoute = AiFeedRouteImport.update({
  id: '/ai-feed',
  path: '/ai-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CybersecurityRoute = CybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleRoute = VehicleRouteImport.update({
  id: '/vehicle',
  path: '/vehicle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-feed': typeof AiFeedRoute
  '/analytics': typeof AnalyticsRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/hub': typeof HubRoute
  '/research': typeof ResearchRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-feed': typeof AiFeedRoute
  '/analytics': typeof AnalyticsRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/hub': typeof HubRoute
  '/research': typeof ResearchRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-feed': typeof AiFeedRoute
  '/analytics': typeof AnalyticsRoute
  '/cybersecurity': typeof CybersecurityRoute
  '/hub': typeof HubRoute
  '/research': typeof ResearchRoute
  '/vehicle': typeof VehicleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-feed'
    | '/analytics'
    | '/cybersecurity'
    | '/hub'
    | '/research'
    | '/vehicle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-feed'
    | '/analytics'
    | '/cybersecurity'
    | '/hub'
    | '/research'
    | '/vehicle'
  id:
    | '__root__'
    | '/'
    | '/ai-feed'
    | '/analytics'
    | '/cybersecurity'
    | '/hub'
    | '/research'
    | '/vehicle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiFeedRoute: typeof AiFeedRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CybersecurityRoute: typeof CybersecurityRoute
  HubRoute: typeof HubRoute
  ResearchRoute: typeof ResearchRoute
  VehicleRoute: typeof VehicleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-feed': {
      id: '/ai-feed'
      path: '/ai-feed'
      fullPath: '/ai-feed'
      preLoaderRoute: typeof AiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cybersecurity': {
      id: '/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/cybersecurity'
      preLoaderRoute: typeof CybersecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle': {
      id: '/vehicle'
      path: '/vehicle'
      fullPath: '/vehicle'
      preLoaderRoute: typeof VehicleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiFeedRoute: AiFeedRoute,
  AnalyticsRoute: AnalyticsRoute,
  CybersecurityRoute: CybersecurityRoute,
  HubRoute: HubRoute,
  ResearchRoute: ResearchRoute,
  VehicleRoute: VehicleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
